import Dispatcher from 'dispatcher/AppDispatcher';


/**
 * `Actions` are generated by `Views` and processed by the `Dispacher` according to the
 * Flux application architecture.
 *
 */
const Actions = {

  TYPES: {
    'SET': 'SET',
    'ADD': 'ADD',
  },

  set: (val) => {
    Dispatcher.handleViewAction({
      type: Actions.TYPES.SET,
      value: val
    });
  },

  add: (n) => {
    Dispatcher.handleViewAction({
      type: Actions.TYPES.ADD,
      n
    });
  }
};

/**
 * Expose `Actions`
 */

exports = module.exports = Actions;
